export const myproject = [
  {
    projecttitle: "NEXCENT",
    category: ["react"],
    imgpath: "/1.png",
    p: "  Built a responsive  website using HTML, CSS,TailwingCss, JavaScript and React. Designed interactive pages including home, Service, about, Product, Testimonial and FAQ sections with modern UI/UX, custom fonts, and dynamic features like image sliders and smooth scrolling.",
    link: "https://ahmedgamal53.github.io/NEXCENT/",
  },
  {
    projecttitle: "Templet",
    category: ["css"],
    imgpath: "/2.png",
    p: "  Built a fully responsive  website using HTML and CSS. Designed and structured interactive pages including Articles, Gallery, Features, and other essential sections. Focused on creating a clean layout, smooth navigation, and a modern user experience across all devices.",
    link: "https://ahmedgamal53.github.io/example-3/",
  },
  {
    projecttitle: "Dashboard",
    category: ["css"],
    imgpath: "/3.png",
    p: "  Built a responsive  website using HTML And CSS  Designed interactive pages including Dashboard, Settings, Profile, Projects, Courses and Plans sections with modern UI/UX, custom fonts.",
    link: "https://ahmedgamal53.github.io/example-4/",
  },
  {
    projecttitle: "Login",
    category: ["css"],
    imgpath: "/4.png",
    p: "  Developed a responsive login page using HTML and CSS. Designed with a clean UI, centered form, and responsive layout that adapts perfectly to different screen sizes.",
    link: "https://ahmedgamal53.github.io/login/",
  },
  {
    projecttitle: "Special Design",
    category: ["js"],
    imgpath: "/5.png",
    p: "  Built a responsive  website using HTML , CSS And Javascript. Designed interactive pages including About, Skills, Gallery, Timeline, Features and Testimonials sections with modern UI/UX, custom fonts, and dynamic features like image sliders and smooth scrolling.",
    link: "https://ahmedgamal53.github.io/login/",
  },
  {
    projecttitle: "Quiz App",
    category: ["js"],
    imgpath: "/6.png",
    p: " Welcome to our interactive quiz platform — built using HTML, CSS, and JavaScript to provide a fast and engaging experience. Explore a variety of topics, get instant feedback, and track your progress as you improve your knowledge and skills.",
    link: "https://ahmedgamal53.github.io/special_design_1/",
  },
  {
    projecttitle: "Guess The Word",
    category: ["js"],
    imgpath: "/7.png",
    p: "  Built a responsive  website using HTML , CSS And Javascript. Designed interactive pages including About, Skills, Gallery, Timeline, Features and Testimonials sections with modern UI/UX, custom fonts, and dynamic features like image sliders and smooth scrolling.",
    link: "https://ahmedgamal53.github.io/Guess--The-Word-Game/",
  },
];
